import { Webtoon, Platform, SerializationStatus } from '@models/webtoon';

export const dummyBookmarkedWebtoons: Webtoon[] = [
  {
    id: 1,
    title: '전지적 독자 시점',
    thumbnailUrl: 'https://via.placeholder.com/200x300/667eea/ffffff?text=Webtoon1',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.ONGOING,
    publishDay: '월요일',
    authors: [{ id: 1, role: '작가', name: '슬리피-C' }],
    description: '소설 속 세계에 빙의한 독자의 이야기',
    genres: [{ id: 1, name: '액션' }, { id: 2, name: '판타지' }],
    totalRatings: 1250,
    averageRating: 4.8,
    similarWebtoons: null
  },
  {
    id: 2,
    title: '여신강림',
    thumbnailUrl: 'https://via.placeholder.com/200x300/f093fb/ffffff?text=Webtoon2',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.ONGOING,
    publishDay: '화요일',
    authors: [{ id: 2, role: '작가', name: '야옹이' }],
    description: '화장을 하면 예뻐지는 여자의 이야기',
    genres: [{ id: 3, name: '로맨스' }, { id: 4, name: '일상' }],
    totalRatings: 980,
    averageRating: 4.6,
    similarWebtoons: null
  },
  {
    id: 3,
    title: '독립일기',
    thumbnailUrl: 'https://via.placeholder.com/200x300/4facfe/ffffff?text=Webtoon3',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.ONGOING,
    publishDay: '수요일',
    authors: [{ id: 3, role: '작가', name: '자까' }],
    description: '독립한 후의 일상 이야기',
    genres: [{ id: 4, name: '일상' }, { id: 5, name: '에세이' }],
    totalRatings: 2100,
    averageRating: 4.9,
    similarWebtoons: null
  },
  {
    id: 4,
    title: '갓 오브 하이스쿨',
    thumbnailUrl: 'https://via.placeholder.com/200x300/43e97b/ffffff?text=Webtoon4',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.ONGOING,
    publishDay: '목요일',
    authors: [{ id: 4, role: '작가', name: '박용제' }],
    description: '고등학생들의 격투 대회 이야기',
    genres: [{ id: 1, name: '액션' }, { id: 2, name: '판타지' }],
    totalRatings: 1560,
    averageRating: 4.7,
    similarWebtoons: null
  },
  {
    id: 5,
    title: '스위트홈',
    thumbnailUrl: 'https://via.placeholder.com/200x300/ff6b6b/ffffff?text=Webtoon5',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.COMPLETED,
    publishDay: '금요일',
    authors: [{ id: 5, role: '작가', name: '김칸비' }],
    description: '아파트에서 벌어지는 생존 이야기',
    genres: [{ id: 6, name: '스릴러' }, { id: 7, name: '호러' }],
    totalRatings: 890,
    averageRating: 4.5,
    similarWebtoons: null
  },
  {
    id: 6,
    title: '나 혼자만 레벨업',
    thumbnailUrl: 'https://via.placeholder.com/200x300/667eea/ffffff?text=Webtoon6',
    platform: Platform.NAVER,
    isAdult: false,
    status: SerializationStatus.ONGOING,
    publishDay: '토요일',
    authors: [{ id: 6, role: '작가', name: '추공' }],
    description: '게임처럼 레벨업하는 현실 세계',
    genres: [{ id: 1, name: '액션' }, { id: 2, name: '판타지' }],
    totalRatings: 1780,
    averageRating: 4.8,
    similarWebtoons: null
  }
]; 